import {
  Award,
  Banknote,
  Briefcase,
  Calculator,
  CalendarRange,
  ChartSpline,
  ClipboardCheck,
  ConciergeBell,
  FileText,
  FlaskConical,
  FolderKanban,
  Handshake,
  LayoutDashboard,
  ListChecks,
  MessageSquareWarning,
  Network,
  NotebookPen,
  Palette,
  Rocket,
  Scale,
  ScrollText,
  SearchCheck,
  Settings2,
  ShieldCheck,
  SprayCan,
  Store,
  Table2,
  TrendingUp,
  UserRound,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/** Maps nav icon names (strings in nav.ts) to Lucide components. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  LayoutDashboard,
  ChartSpline,
  ListChecks,
  CalendarRange,
  ConciergeBell,
  SprayCan,
  MessageSquareWarning,
  Store,
  Users,
  Network,
  ScrollText,
  FileText,
  Award,
  Calculator,
  Table2,
  // Division (group) icons
  Briefcase,
  ShieldCheck,
  FlaskConical,
  Scale,
  Settings2,
  // Department-aligned division icons (name-matched)
  UserRound,
  Wallet,
  Banknote,
  Palette,
  FolderKanban,
  SearchCheck,
  ClipboardCheck,
  NotebookPen,
  Handshake,
  Rocket,
  TrendingUp,
};
