import {
  Briefcase,
  CalendarRange,
  ChartSpline,
  ConciergeBell,
  FileText,
  FlaskConical,
  LayoutDashboard,
  ListChecks,
  MessageSquareWarning,
  Network,
  Scale,
  ScrollText,
  Settings2,
  ShieldCheck,
  SprayCan,
  Store,
  Users,
  type LucideIcon,
} from "lucide-react";

/** Maps nav icon names (strings in nav.ts) to Lucide components. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  LayoutDashboard,
  ChartSpline,
  ListChecks,
  CalendarRange,
  ConciergeBell,
  SprayCan,
  MessageSquareWarning,
  Store,
  Users,
  Network,
  ScrollText,
  FileText,
  // Division (group) icons
  Briefcase,
  ShieldCheck,
  FlaskConical,
  Scale,
  Settings2,
};
